server:
  port: 8081
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xkql?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    username: 17575010142@163.com
    password: HNXW4LW7ScMycf9R
    port: 465
    properties:
      from: 17575010142@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 512MB

---
spring:
  config:
    activate:
      on-profile: dev
static-path: backend/static

---
spring:
  config:
    activate:
      on-profile: test
static-path: /www/wwwroot/xkql/backend/static

---
spring:
  config:
    activate:
      on-profile: prod
static-path: /www/wwwroot/xkql/backend/static

---
spring:
  config:
    activate:
      on-profile: BackendApplication
static-path: backend/static